services:
  node:
    container_name: fleet_node
    hostname: fleet_node
    build: ./docker/compose/node
    command: bash -c "tail -f /dev/null"
    working_dir: /home/node/app
    restart: always
    volumes:
      - .:/home/node/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    networks:
      - fleet_network
  nginx:
    container_name: fleet_nginx
    image: nginx:latest
    hostname: fleet_nginx
    restart: always
    volumes:
      - ./docker/compose/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - fleet_network
networks:
  fleet_network:
    name: fleet_network
    driver: bridge

